version: '2'
services:
  cam-privacy-api:
    env_file: .env
    restart: on-failure
    image: cam-privacy
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:9090:8080"
